codeX/urls.py
from django.urls import path

from . import views

app_name='codeX'
urlpatterns = [
    path('', views.Top.as_view(), name="top"),
    path('edit/<int:pk>/', views.Edit.as_view(), name='edit'),
    path('update/<int:pk>/', views.Update.as_view(), name='update'),
    path('update_page/<int:pk>/<int:mod_id>/<str:mod>/', views.update_page, name='update_page'),
    path('delete/<int:pk>/<int:mod_id>/<str:mod>/', views.delete, name='delete'),
    path('profile/', views.Profile.as_view(), name='profile'),
    path('update_profile/<int:pk>/', views.UpdateProfile.as_view(), name='update_profile'),
    path('login/',views.LoginPage.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('password_change/', views.PasswordChange.as_view(), name='change_password'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='change_password_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='reset_password'), 
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='reset_password_done'), 
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='reset_password_confirm'), 
    path('reset/done/', views.PasswordResetComplete.as_view(), name='reset_password_complete'), 
]

help/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from . import views

app_name='help'
urlpatterns = [
    path('top/', views.Top.as_view(), name='top'),
    path('news/<int:pk>/', views.NewsView.as_view(), name='news'),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/X/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>X {% block title %}{% endblock %}</title>
    {% block additional_css %}{% endblock %}
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/x.min.css' %}">
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+1p&display=swap" rel="stylesheet">
  </head>
  <body>
    <div class="wrapper">
      <div class="container">
        {% block content %}{% endblock %}
      </div>
    </div>
    <div class="heading">
      <a href="{% url 'codeX:top' %}"><img class="logo" src="{% static 'img/codex_logo_2.svg' %}" alt="Site Icon"></a>
      {% block additional_head %}{% endblock %}
      <div id="nav-wrap">
        <div id="nav" class="nav">
          <div id="hum" class="hum">
          <div>
            <span></span> <span></span> <span></span>
          </div>
          </div>
        </div>
      </div>
    </div>
    <div class="side-wrapper">
      <div id="sideBar" class="side-bar display">
        <div class="side-text">
          <a href="{% url 'codeX:top' %}">Top</a>
        </div>
        {% if user.is_authenticated %}
          <div class="side-text">
            <a href="{% url 'codeX:profile' %}">Profile</a>
          </div>
          <div class="side-text">
            <a href="{% url 'codeX:logout' %}">logout</a> 
          </div>
        {% else %}
          <div class="side-text">
            <a href="{% url 'codeX:login' %}">login</a>
          </div>
        {% endif %}
        
        {% block sidebar %}
        {% endblock %}
      </div>   
    </div>
    <script src="{% static 'js/x.js' %}"></script>
    {% block additional_js %}{% endblock %}
  </body>
</html>

templates/X/change_password.html
{% extends "X/base.html" %}
{% block content %}
<div class="margin-top-more">
  <form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="section">
      <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
      {{ field }}
      {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="sub-btn">送信</button>
  </form>
</div>
{% endblock %}

templates/X/change_password_done.html
{% extends 'X/base.html' %}

{% block content %}
<div class="margin-top-more">
  <p>パスワード再設定を完了しました。</p>
  <a class="" href="{% url 'codeX:top' %}">topへ</a>
</div>
{% endblock %}

templates/X/edit.html
{% extends 'X/base.html' %}

{% block title %} edit {% endblock %}
{% block content %}
<div class="div-text">
  現時点では個別送信のみの対応となっております。<span class="strong">送信したい項目のチェックボタンをクリックして</span>　送信してください。ご理解とご協力のほどお願いいたします。
</div>
<div>
  {% if messages %}
    {% for m in messages %}
      <div class="section {{ m.tags }}-text">{{ m|safe }}</div>
    {% endfor %}
  {% endif %}
</div>
{% for k, form in forms.items %} 
  <div class="section-title is-edit">{{ k }}</div>
  <form class="edit-form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form{{ forloop.counter }}" id="form{{ forloop.counter }}">
      <div id="form-{{ forloop.counter }}">
        {% for f in form %}
          <div class="edit-form-content">
            <label class="edit-form-label" for="f">{{ f.label }}</label>
            <div class="edit-form-text">{{ f.help_text }}</div>
            <div>{{ f }}</div>
          </div>
        {% endfor %}
      </div>
    </div>
    <button class="sub-btn" type="submit">save </button>
  </form>
{% empty %}
  <p>the list is empty.</p>
{% endfor %}
  

{% endblock %}

templates/X/login.html
{% extends 'X/base.html' %}
{% load widget_tweaks %}

{% block title %} login {% endblock %}
{% block content %}
<div class="margin-top-more">
  {% for field, errors in form.errors.items %}
    <ul>
      {% for error in errors %}
        <li class="create-error">{{ error }}</li>
      {% endfor %}
    </ul>
  {% endfor %}
  <form class="login-form" method="post">
    {% csrf_token %}
    <p>{{ form.username.label }}</p>
    <p>{{ form.username|add_class:"text-form" }}</p>
    <p>{{ form.password.label }}</p>
    <p>{{ form.password|add_class:"pass-form" }}</p>
    <button class="sub-btn login-page" type="submit">ログイン</button>
    <div class="login-text">
      <a href="{% url 'codeX:reset_password' %}">パスワードを忘れた方はこちらから</a>
    </div>
  </form>
 


</div>
{% endblock %}

templates/X/profile.html
{% extends 'X/base.html' %}

{% block title %} edit {% endblock %}
{% block content %}
<div class="div-text">
  <h1>現在の{{ user.username }}様の情報</h1>
  <p class="with-p">UserID: {{ user.user_id }}</p>
  <p class="with-p">Username: {{ user.username }}</p>
  <p class="with-p">Email: {{ user.email }}</p>
  
  <div class="section">
    <a href="{% url 'codeX:update_profile' user.id %}">ユーザーデータを変更する</a>
  </div>  

  <div class="section">
    <a href="{% url 'codeX:change_password' %}">パスワードの変更はこちらから</a>
  </div> 

</div>
  

{% endblock %}

templates/X/reset_password_complete.html
{% extends 'X/base.html' %}

{% block content %}
  <p>パスワード再設定を完了しました。</p>
  <a class="" href="{% url 'codeX:top' %}">ログイン</a>
{% endblock %}

templates/X/reset_password_confirm.html
{% extends 'X/base.html' %}
{% load widget_tweaks %}

{% block title %} パスワード再設定 {% endblock %}

{% block content %}

<form action="" method="POST">
  {{ form.non_field_errors }}
  {% for field in form %}
  <div class="section">
    <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
    {{ field|add_class:"pass-form" }}
    {{ field.errors }}
  </div>
  {% endfor %}
  {% csrf_token %}
  <button type="submit" class="sub-btn">送信</button>
</form>
{% endblock %}

templates/X/reset_password_done.html
{% extends 'X/base.html' %}

{% block title %} パスワード再設定 {% endblock %}

{% block content %}
  <div class="margin-top-more">
    <p>パスワードリセットのメールを送信しました。</p>
    <p>メールに記載されているリンクからパスワードの再設定を行ってください。</p>
    <a class="" href="{% url 'codeX:top' %}">ログイン画面へ</a>
  </div>
{% endblock %}

templates/X/reset_password_form.html
{% extends 'X/base.html' %}
{% load widget_tweaks %}

{% block title %} パスワード再設定 {% endblock %}

{% block content %}
<div class="margin-top-more">
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <p>パスワードの変更手続きを行います。本人確認のためメールを使用します。</p>
    <p>メールアドレスを入力して、下記の送信ボタンを押してください。</p>
    {% for field in form %}
      <div class="section">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field|add_class:"text-form pass-form" }}
        {{ field.errors }}
      </div>
    {% endfor %}
    <button type="submit" class="sub-btn">送信</button>

  </form>
  <div class="">
    <p>メールアドレスは登録されたものを使用してください。</p>
    <p>登録されたもの以外ではメールが送信されません。</p>
    <p>困ったことがありましたらシステム管理者にご連絡ください</p>
  </div>
</div>
{% endblock %}

templates/X/top.html
{% extends 'X/base.html' %}
{% load static %}
{% load hosts %}
{% block additional_head %}
{% if user.is_authenticated %}
  <div class="head-text">ようこそ {{ request.user.username }}</div>
{% endif %}
{% endblock %}
{% block content %}
{% if user.is_authenticated %}
  <h1 class="head1-title">{{ request.user.username }}様の保有しているサイト一覧</h1>
  {% for site in sites %}
    <div class="site-box">
      <div class="site-box-text">{{ site }}</div>
      <div class="top-btn">
        <a href="{% url 'codeX:edit' site.id %}">
          新規作成
        </a>
        <a href="{% url 'codeX:update' site.id %}">
          更新・削除
        </a>
      </div>
    </div>
  {% endfor %}
{% else %}
  <img class="top-logo" src="{% static 'img/codex_logo_2.svg' %}" alt="Site Icon" />
  <img class="top-message-im" src="{% static 'img/codex_top_text.svg' %}" alt="サイトの更新もっと簡単に"/>

  <a class="case-not-login-nav" href="{% host_url 'top' host 'help' %}">codeXとは？<br>ログインするには？</a>

  <a class="case-not-login" href="{% url 'codeX:login' %}">ログイン</a> 
  
  <div class="section top-text-not-login">
    <a href="{% url 'codeX:reset_password' %}">パスワードを忘れた方はこちらから</a>
  </div> 
  
  
{% endif %}
{% endblock %}

templates/X/update.html
{% extends 'X/base.html' %}
{% load get_array %}

{% block title %} update {% endblock %}
{% block content %}

<div class="margin-top">
  {% if messages %}
    {% for m in messages %}
      <div class="div-text section {{ m.tags }}-text" style="text-align: center;">{{ m|safe }}</div>
    {% endfor %}
  {% endif %}
  {% for key, item in items.items %}
    <div class="section">
      <h2 class="section-title">{{ key }}</h2>
      <div class="update-box">
        {% with name=model_name|get_array_value:forloop.counter0 %}
          {% for i in item %}
            <div class="update-content">
              <div class="update-content-text">{{ i }} </div>
              {% if i.can_update %}
                <a class="upd-sub-btn" href="{% url 'codeX:update_page' site_id i.id name %}">更新</a>
              {% endif %}
                <a class="del-sub-btn" href="{% url 'codeX:delete' site_id i.id name %}" data-item="{{ i }}" onclick="DeleteItem(this, event)">削除</a>
            </div>
          {% endfor %}
        {% endwith %}
      </div>
    </div>
  {% empty %}
    <p>
      更新や削除できる項目が見つかりません。
      お困りの際はは開発担当へご連絡くださいませ。
    </p>
  {% endfor %}
</div>  

{% endblock %}
{% block additional_js %}
<script>
  function DeleteItem ($this, e) {
    let data = $this.dataset.item
    let ret = window.confirm(`${data}を削除してもよろしいですか？`)
    if(!ret){ 
      e.preventDefault()
    }
  }
</script>
{% endblock %}

templates/X/update_page.html
{% extends 'X/base.html' %}

{% block title %} edit {% endblock %}
{% block content %}
  
  {% if messages %}
    {% for m in messages %}
      <div class="div-text section {{ m.tags }}-text">{{ m|safe }}</div>
    {% endfor %}
  {% endif %}

  <div class="div-text">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form{{ num }}" id="form{{ num }}">
        <div id="form-{{ num }}">
          {% for f in form %}
            <div class="edit-form-content">
              <label class="edit-form-label" for="f">{{ f.label }}</label>
              <div class="edit-form-text">{{ f.help_text }}</div>
              <div>{{ f }}</div>
            </div>
          {% endfor %}
        </div>
      </div>
      <button class="sub-btn" type="submit">save </button>
    </form>
  </div>


{% endblock %}

templates/X/update_profile.html
{% extends 'X/base.html' %}

{% block title %} edit {% endblock %}
{% block content %}
  {% if messages %}
    {% for m in messages %}
      <div class="div-text section {{ m.tags }}-text">{{ m|safe }}</div>
    {% endfor %}
  {% endif %}

<div class="div-text">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form{{ num }}" id="form{{ num }}">
      <label for="form-{{ num }}">{{ form.label }}</label>
      <div id="form-{{ num }}">
        {{ form.as_p }}
      </div>
    </div>
    <button class="sub-btn" type="submit">save </button>
  </form>
</div>


{% endblock %}